version: 0.2

phases:
  pre_build:
    commands:
      # Single ECR login using the registry base URL
      - REGISTRY=$(echo $FRONTEND_ECR | cut -d/ -f1)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REGISTRY
      - echo "Logged into ECR registry $REGISTRY"

  build:
    commands:
      - docker build -t client:latest app/client
      - docker tag client:latest $FRONTEND_ECR:latest

      - docker build -t server:latest app/server
      - docker tag server:latest $BACKEND_ECR:latest

  post_build:
    commands:
      - docker push $FRONTEND_ECR:latest
      - docker push $BACKEND_ECR:latest

      # imagedefinitions.json — container names MUST match task definition exactly
      - |
        printf '[{"name":"client","imageUri":"%s"},{"name":"server","imageUri":"%s"}]' \
          $FRONTEND_ECR:latest \
          $BACKEND_ECR:latest > imagedefinitions.json

      # Render taskdef.json with real values for CodeDeploy blue-green
      - |
        sed -e "s|<IMAGE1_NAME>|$BACKEND_ECR:latest|g" \
            -e "s|<IMAGE2_NAME>|$FRONTEND_ECR:latest|g" \
            -e "s|<EXECUTION_ROLE_ARN>|$TASK_EXECUTION_ROLE_ARN|g" \
            -e "s|<SECRET_ARN>|$SECRET_ARN|g" \
            -e "s|<AWS_REGION>|$AWS_REGION|g" \
            -e "s|<DB_HOST>|$DB_HOST|g" \
            -e "s|<DB_NAME>|$DB_NAME|g" \
            taskdef.json > taskdef_rendered.json && mv taskdef_rendered.json taskdef.json

      - echo "=== appspec.yaml ===" && cat appspec.yaml
      - echo "=== taskdef.json ===" && cat taskdef.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - taskdef.json
  discard-paths: yes
