version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $FRONTEND_ECR
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $BACKEND_ECR

  build:
    commands:
      - docker build -t client:latest app/client
      - docker tag client:latest $FRONTEND_ECR:latest

      - docker build -t server:latest app/server
      - docker tag server:latest $BACKEND_ECR:latest

  post_build:
    commands:
      - docker push $FRONTEND_ECR:latest
      - docker push $BACKEND_ECR:latest

      # imagedefinitions.json — container names MUST match task definition exactly
      - |
        printf '[{"name":"client","imageUri":"%s"},{"name":"server","imageUri":"%s"}]' \
          $FRONTEND_ECR:latest \
          $BACKEND_ECR:latest > imagedefinitions.json

      # Generate taskdef.json dynamically with real image URIs for CodeDeploy blue-green
      - |
        sed -e "s|<IMAGE1_NAME>|$BACKEND_ECR:latest|g" \
            -e "s|<IMAGE2_NAME>|$FRONTEND_ECR:latest|g" \
            -e "s|<EXECUTION_ROLE_ARN>|$TASK_EXECUTION_ROLE_ARN|g" \
            taskdef.json > taskdef_rendered.json && mv taskdef_rendered.json taskdef.json

      # Verify appspec.yaml is present (must be committed to repo)
      - cat appspec.yaml

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - taskdef.json
